CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    _url TEXT,
    _description TEXT,
    rating INTEGER,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL
);